# Generated by Django 4.1.7 on 2023-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=100)),
                ('producer', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
